### PR TITLE
fix: support legacy api routes, add types, redirect private routes and loading state tokens

### LINKED ISSUE #76: add loading to tokens view

### LINKED ISSUE #78: fix redirects to nft.storage/*

### LINKED ISSUE #79: fix CI deploy for production
upsert dns record fails for bare domain `nft.storage`

### LINKED ISSUE #81: private routes are not redirecting properly when logged out

### PR DESCRIPTION
**Pull request by hugomrdias**
- add support for legacy api endpoint `/api/*`
- adds types to the frontend code with typecheck
- add loading state in the api keys view
- fix redirects to homepage when logout

closes #81 
closes #76 
closes #78 
closes #79

### CODE REVIEW

File: site/src/index.js [hunk 1]
```diff
@@ -55,19 +55,30 @@ r.add('get', '/version', () => {
...
+r.add('post', '/api/upload', upload, [postCors])
+r.add('delete', '/api/:cid', remove, [postCors])
+
 r.add('get', '', list, [postCors])
 r.add('get', '/:cid', status, [postCors])
+r.add('post', '/upload', upload, [postCors])
 r.add('delete', '/:cid', remove, [postCors])
 
-// Private API
+// // Private API
```
Comment (alanshaw) [inline site/src/index.js:81]:
```suggestion
// Private API
```

File: website/pages/callback.js [hunk 2]
```diff
@@ -1,43 +1,51 @@
...
   const router = useRouter()
+  const queryClient = useQueryClient()
   useEffect(() => {
     const finishSocialLogin = async () => {
       try {
         await redirectSocial()
         router.push('/files')
-      } catch (error) {
+      } catch (err) {
+        queryClient.invalidateQueries('magic-user')
```
Comment (alanshaw) [inline website/pages/callback.js:29]: Not smother!

```suggestion
      } catch (err) {
        console.error(err)
        queryClient.invalidateQueries('magic-user')
```

File: website/pages/callback.js [hunk 3]
```diff
@@ -1,43 +1,51 @@
...
-          await redirectMagic()
-          router.push('/files')
-        } catch (error) {
-          router.push('/')
-        }
+      try {
+        await redirectMagic()
+        router.push('/files')
+      } catch (err) {
+        queryClient.invalidateQueries('magic-user')
```
Comment (alanshaw) [inline website/pages/callback.js:38]:
```suggestion
      } catch (err) {
        console.error(err)
        queryClient.invalidateQueries('magic-user')
```

File: tools/dns.js [hunk 4]
```diff
@@ -0,0 +1,45 @@
...
+
+cli
+  .version('1.0.0')
+  .option('--token', 'Cloudflare Token')
+  .option('--zone', 'Cloudflare Zone')
+  .option('--name', 'Record name')
+  .option('--content', 'Record content ie. "subdomain.domain.com')
+  .option('--type', 'Record type', 'CNAME')
+  .option('--ttl', 'Record TTL', 1)
+  .option('--proxied', 'Record should proxied ?', true)
```
Comment (alanshaw) [inline tools/dns.js:16]:
```suggestion
  .option('--proxied', 'Record should be proxied?', true)
```

**Review by alanshaw — APPROVED** [review]
💯
